version: '2'
services:
  db:
    image: mysql:5.7
    container_name: tax_calculator_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  app:
    build: .
    container_name: tax_calculator_api
    command:
      "bash -c -l 'bundle install &&
      bundle exec puma'"
    ports:
      - "3003:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ".:/tax_calculator"
    environment:
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db


